export const phenomedSocialEnglishContent = {
  path: "/phenomedsocial",
  switchLabel: "Ar",
  switchTo: "/phenomedsocial/ar",
  eyebrow: "Clinical social workspace",
  title: "Phenomed Social",
  description:
    "A sharper social desk for doctors to publish notes, browse terminology, and connect around clinical reasoning.",
  doctorPrefix: "Dr.",
  metrics: {
    posts: "Posts",
    terms: "Terms",
    friends: "Friends",
  },
  terminology: {
    title: "Terminology",
    termPlaceholder: "Enter a medical term",
    meaningPlaceholder: "What does it mean ..",
    categoryPlaceholder: "System",
    subjectPlaceholder: "Discipline",
    postButton: "Post",
  },
  inputPost: {
    notePlaceholder: "Want to post a note?",
    categoryPlaceholder: "System",
    subjectPlaceholder: "Discipline",
    resourcePlaceholder: "Resource",
    pagePlaceholder: "Page Number",
    postButton: "Post",
  },
  search: {
    button: "Search",
    addFriendsPlaceholder: "Search new doctors",
    currentFriendsPlaceholder: "Search current friends",
  },
  friends: {
    empty: "You have no friends to show",
  },
  chat: {
    title: "Chat",
    onlineLabel: "online",
    offlineLabel: "offline",
    typingLabel: "typing...",
    empty: "Open a conversation to view messages here.",
    inputPlaceholder: "Write a message",
  },
  categories: [
    "General Principles",
    "Behavioral health system",
    "Nervous system",
    "Respiratory system",
    "Renal system",
    "Reproductive system",
    "Female reproductive system",
    "Male reproductive system",
    "Endocrine system",
    "Blood system",
    "Immune system",
    "Multisystem processes and disorders",
    "Musculoskeletal tissue",
    "Skin and subcutaneous tissue",
    "Cardiovascular system",
    "Gastrointestinal system",
    "Biostatistics and population health",
    "Social sciences: communication skills and ethics",
  ],
  subjects: [
    "Pathology",
    "Physiology",
    "Pharmacology",
    "Biochemistry: Molecular",
    "Biochemistry: Cellular",
    "Biochemistry: Lab Tech",
    "Biochemistry: Genetics",
    "Biochemistry: Nutrition",
    "Biochemistry: Metabolism",
    "Microbiology",
    "Immunology",
    "Gross Anatomy",
    "Embryology",
    "Histology",
    "Cell Biology",
    "Behavioral Sciences",
    "Genetics",
  ],
};

export const phenomedSocialArabicContent = {
  path: "/phenomedsocial/ar",
  switchLabel: "En",
  switchTo: "/phenomedsocial",
  eyebrow: "مساحة اجتماعية سريرية",
  title: "فينوميد سوشال",
  description:
    "مساحة اجتماعية أكثر احترافًا للأطباء لنشر الملاحظات، واستعراض المصطلحات، والتواصل حول التفكير السريري.",
  doctorPrefix: "د.",
  metrics: {
    posts: "المنشورات",
    terms: "المصطلحات",
    friends: "الأصدقاء",
  },
  terminology: {
    title: "المصطلحات",
    termPlaceholder: "أدخل مصطلحًا طبيًا",
    meaningPlaceholder: "ما معنى هذا المصطلح؟",
    categoryPlaceholder: "الجهاز",
    subjectPlaceholder: "التخصص",
    postButton: "نشر",
  },
  inputPost: {
    notePlaceholder: "هل تريد نشر ملاحظة؟",
    categoryPlaceholder: "الجهاز",
    subjectPlaceholder: "التخصص",
    resourcePlaceholder: "المرجع",
    pagePlaceholder: "رقم الصفحة",
    postButton: "نشر",
  },
  search: {
    button: "بحث",
    addFriendsPlaceholder: "ابحث عن أطباء جدد",
    currentFriendsPlaceholder: "ابحث في الأصدقاء الحاليين",
  },
  friends: {
    empty: "لا يوجد أصدقاء لعرضهم",
  },
  chat: {
    title: "المحادثة",
    onlineLabel: "متصل",
    offlineLabel: "غير متصل",
    typingLabel: "يكتب الآن...",
    empty: "افتح محادثة لعرض الرسائل هنا.",
    inputPlaceholder: "اكتب رسالة",
  },
  categories: [
    "المبادئ العامة",
    "جهاز الصحة السلوكية",
    "الجهاز العصبي",
    "الجهاز التنفسي",
    "الجهاز الكلوي",
    "الجهاز التناسلي",
    "الجهاز التناسلي الأنثوي",
    "الجهاز التناسلي الذكري",
    "جهاز الغدد الصماء",
    "جهاز الدم",
    "الجهاز المناعي",
    "عمليات واضطرابات متعددة الأجهزة",
    "الأنسجة العضلية الهيكلية",
    "الجلد والأنسجة تحت الجلد",
    "الجهاز القلبي الوعائي",
    "الجهاز الهضمي",
    "الإحصاء الحيوي وصحة السكان",
    "العلوم الاجتماعية: مهارات التواصل والأخلاقيات",
  ],
  subjects: [
    "علم الأمراض",
    "علم وظائف الأعضاء",
    "علم الأدوية",
    "الكيمياء الحيوية: جزيئية",
    "الكيمياء الحيوية: خلوية",
    "الكيمياء الحيوية: تقنيات مخبرية",
    "الكيمياء الحيوية: الوراثة",
    "الكيمياء الحيوية: التغذية",
    "الكيمياء الحيوية: الأيض",
    "علم الأحياء الدقيقة",
    "علم المناعة",
    "التشريح العياني",
    "علم الأجنة",
    "علم النسج",
    "علم الأحياء الخلوي",
    "العلوم السلوكية",
    "علم الوراثة",
  ],
};
